name = "kokosos-api"
main = "src/index.ts"
compatibility_date = "2024-09-10"
legacy_env = true

[[migrations]]
tag = "v1-alert-hub-sqlite"
new_sqlite_classes = ["AlertHub"]

[env.dev]
name = "kokosos-api-dev"
[env.dev.durable_objects]
bindings = [{ name = "ALERT_HUB", class_name = "AlertHub" }]

[env.stage]
name = "kokosos-api-stage"
[env.stage.durable_objects]
bindings = [{ name = "ALERT_HUB", class_name = "AlertHub" }]

[env.prod]
name = "kokosos-api-prod"
[env.prod.durable_objects]
bindings = [{ name = "ALERT_HUB", class_name = "AlertHub" }]

#[vars]
# Placeholders for local dev; production uses Secrets
# JWT_SECRET = "..."
# SUPABASE_URL = "..."
# SUPABASE_SERVICE_ROLE_KEY = "..."
# CORS_ALLOW_ORIGIN = "..."

# [miniflare]  # used only for local `wrangler dev`
# kv_persist = true
# durable_objects_persist = true
# cache_persist = true
