name = "kokosos-api"
main = "src/index.ts"
compatibility_date = "2024-09-10"

[vars]
# Populated from environment or Wrangler secrets
# JWT_SECRET = "..."
# SUPABASE_URL = "..."
# SUPABASE_SERVICE_ROLE_KEY = "..."
# SES_REGION = "..."
# SES_ACCESS_KEY_ID = "..."
# SES_SECRET_ACCESS_KEY = "..."
# SES_SENDER_EMAIL = "..."

[miniflare]
kv_persist = true
durable_objects_persist = true
cache_persist = true

[env.dev]
name = "kokosos-api-dev"

[env.stage]
name = "kokosos-api-stage"

[env.prod]
name = "kokosos-api-prod"
