name: KokoSOS
options:
  bundleIdPrefix: com.kokosos
  deploymentTarget:
    iOS: '15.0'
  developmentLanguage: ja
configs:
  Debug-Dev: debug
  Debug-Stage: debug
  Debug-Prod: debug
  Release-Dev: release
  Release-Stage: release
  Release-Prod: release
settings:
  base:
    PRODUCT_NAME: KokoSOS
    PRODUCT_BUNDLE_IDENTIFIER: $(APP_BUNDLE_ID)
    TARGETED_DEVICE_FAMILY: 1
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 0.1.0
    SWIFT_VERSION: 5.0
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  configs:
    Debug-Dev:
      GCC_PREPROCESSOR_DEFINITIONS: DEBUG=1
      INFOPLIST_FILE: Resources/Info-Dev.plist
      GCC_OPTIMIZATION_LEVEL: 0
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG DEV
      BASE_CONFIGURATION: Configs/Dev.xcconfig
    Debug-Stage:
      GCC_PREPROCESSOR_DEFINITIONS: DEBUG=1
      INFOPLIST_FILE: Resources/Info-Stage.plist
      GCC_OPTIMIZATION_LEVEL: 0
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG STAGE
      BASE_CONFIGURATION: Configs/Stage.xcconfig
    Debug-Prod:
      GCC_PREPROCESSOR_DEFINITIONS: DEBUG=1
      INFOPLIST_FILE: Resources/Info-Prod.plist
      GCC_OPTIMIZATION_LEVEL: 0
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG PROD
      BASE_CONFIGURATION: Configs/Prod.xcconfig
    Release-Dev:
      INFOPLIST_FILE: Resources/Info-Dev.plist
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEV
      SWIFT_OPTIMIZATION_LEVEL: '-O'
      BASE_CONFIGURATION: Configs/Dev.xcconfig
    Release-Stage:
      INFOPLIST_FILE: Resources/Info-Stage.plist
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: STAGE
      SWIFT_OPTIMIZATION_LEVEL: '-O'
      BASE_CONFIGURATION: Configs/Stage.xcconfig
    Release-Prod:
      INFOPLIST_FILE: Resources/Info-Prod.plist
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: PROD
      SWIFT_OPTIMIZATION_LEVEL: '-O'
      BASE_CONFIGURATION: Configs/Prod.xcconfig
targets:
  KokoSOS:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Resources
        excludes:
          - "**/*.xcassets/**"
    resources:
      - path: Resources/Assets.xcassets
    scheme:
      testTargets: []
      gatherCoverageData: false
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        SUPPORTED_PLATFORMS: iphonesimulator iphoneos
        OTHER_LDFLAGS: ""
        PRODUCT_BUNDLE_IDENTIFIER: $(APP_BUNDLE_ID)
    info:
      path: Resources/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIApplicationSceneManifest:
              UISceneConfigurationName: Default Configuration
        UILaunchScreen:
          UIColorName: LaunchBackground
        UIRequiresPersistentWiFi: false
        UIRequiresFullScreen: true
        UIStatusBarStyle: UIStatusBarStyleDefault
        UIUserInterfaceStyle: Light
        LSApplicationCategoryType: public.app-category.navigation
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - kokosos
            CFBundleURLName: com.kokosos.oauth
        # Supabase Auth client config (resolved from Build Settings / .xcconfig)
        SupabaseURL: "$(SUPABASE_URL)"
        SupabaseAnonKey: "$(SUPABASE_ANON_KEY)"
        OAuthRedirectScheme: "$(OAUTH_REDIRECT_SCHEME)"
