name: Deploy Web (Cloudflare Pages)

on:
  push:
    branches: [dev, stage, main]

jobs:
  deploy:
    name: Build & Deploy Pages
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'stage' && 'stage' || 'dev' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: apps/web
        run: npm install --no-fund --no-audit

      - name: Build (next-on-pages)
        working-directory: apps/web
        run: npx @cloudflare/next-on-pages@latest
        env:
          NEXT_PUBLIC_API_BASE: ${{ secrets.NEXT_PUBLIC_API_BASE }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ format('kokosos-web-{0}', (github.ref_name == 'main' && 'prod' || github.ref_name == 'stage' && 'stage' || 'dev')) }}
          directory: apps/web/.vercel/output/static
          wranglerVersion: '3'
