name: Deploy API (Cloudflare Workers)

on:
  push:
    branches: [dev, stage, main]

jobs:
  deploy:
    name: Deploy Workers
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'stage' && 'stage' || 'dev' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via Wrangler
        uses: cloudflare/wrangler-action@v3
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          CORS_ALLOW_ORIGIN: ${{ secrets.CORS_ALLOW_ORIGIN }}
          WEB_PUBLIC_BASE: ${{ secrets.WEB_PUBLIC_BASE }}
          EMAIL_PROVIDER: ${{ secrets.EMAIL_PROVIDER }}
        with:
          wranglerVersion: '4.40.3'
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: apps/api-worker
          command: deploy --env ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'stage' && 'stage' || 'dev' }}
          secrets: |
            JWT_SECRET
            SUPABASE_URL
            SUPABASE_SERVICE_ROLE_KEY
            CORS_ALLOW_ORIGIN
