name: Deploy Web (Cloudflare Pages)

on:
  push:
    branches: [dev, stage, main]

jobs:
  deploy:
    name: Build & Deploy Pages
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'stage' && 'stage' || 'dev' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: apps/web
        run: npm install --no-fund --no-audit --legacy-peer-deps

      - name: Build (next-on-pages)
        working-directory: apps/web
        run: npx @cloudflare/next-on-pages@latest
        env:
          NEXT_PUBLIC_API_BASE: ${{ secrets.NEXT_PUBLIC_API_BASE }}
          NEXT_PUBLIC_MAPBOX_TOKEN: ${{ secrets.NEXT_PUBLIC_MAPBOX_TOKEN }}

      - name: Debug CF token env shape
        run: |
          echo "CF_TOKEN_LEN=${#CLOUDFLARE_API_TOKEN}"
          python - <<'PY'
import os
t=os.environ.get('CLOUDFLARE_API_TOKEN','')
print('CF_TOKEN_DEBUG','ENDS_WITH_NL',t.endswith('\n'),'HAS_SPACE',(' ' in t))
PY
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Ensure Pages project exists
        uses: cloudflare/wrangler-action@v3
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: apps/web
          preCommands: |
            npx wrangler whoami || true
            npx wrangler pages project list || true
            npx wrangler pages project create ${{ format('kokosos-web-{0}', (github.ref_name == 'main' && 'prod' || github.ref_name == 'stage' && 'stage' || 'dev')) }} --production-branch=${{ github.ref_name == 'main' && 'main' || github.ref_name == 'stage' && 'stage' || 'dev' }} || true
          command: pages project list


      - name: Deploy via Wrangler Pages
        uses: cloudflare/wrangler-action@v3
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: apps/web
          command: ${{ format('pages deploy .vercel/output/static --project-name={0} --branch={1} --commit-dirty=true --commit-message={2}', format('kokosos-web-{0}', (github.ref_name == 'main' && 'prod' || github.ref_name == 'stage' && 'stage' || 'dev')), (github.ref_name == 'main' && 'main' || github.ref_name == 'stage' && 'stage' || 'dev'), 'GitHub_Actions_Deploy') }}
