name: Deploy Web (Cloudflare Pages)

on:
  push:
    branches: [dev, stage, main]

jobs:
  deploy:
    name: Build & Deploy Pages
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'stage' && 'stage' || 'dev' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: apps/web
        run: npm install --no-fund --no-audit --legacy-peer-deps

      - name: Build (next-on-pages)
        working-directory: apps/web
        run: npx @cloudflare/next-on-pages@latest
        env:
          NEXT_PUBLIC_API_BASE: ${{ secrets.NEXT_PUBLIC_API_BASE }}
          NEXT_PUBLIC_MAPBOX_TOKEN: ${{ secrets.NEXT_PUBLIC_MAPBOX_TOKEN }}

      - name: Install Wrangler (CLI)
        run: npm i -g wrangler@4.41.0

      - name: Ensure & Deploy Pages
        working-directory: apps/web
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          set -euo pipefail
          wrangler whoami
          PROJECT=${{ format('kokosos-web-{0}', (github.ref_name == 'main' && 'prod' || github.ref_name == 'stage' && 'stage' || 'dev')) }}
          BRANCH=${{ github.ref_name == 'main' && 'main' || github.ref_name == 'stage' && 'stage' || 'dev' }}
          wrangler pages project list || true
          wrangler pages project create "$PROJECT" --production-branch="$BRANCH" || true
          wrangler pages deploy .vercel/output/static --project-name="$PROJECT" --branch="$BRANCH" --commit-dirty=true --commit-message="GitHub_Actions_Deploy"
